name: Run Stock Analyzer

on:
  workflow_dispatch:      # allows manual trigger from GitHub
  schedule:
    - cron: '0 6 * * *'    # every day at 6 AM UTC

jobs:
  analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install yfinance pandas matplotlib openpyxl fpdf ta-lib

    - name: Run Analyzer Script
      run: python analyze_stocks.py

    - name: Upload Report PDF
      uses: actions/upload-artifact@v3
      with:
        name: stock-report
        path: stock_report.pdf
